server:
  port: 8189
  servlet:
    context-path: /
spring:
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:example;MODE=PostgreSQL
    username: username
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: swagger-ui.html
